#!/usr/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

# export XDG_CONFIG_HOME="$HOME/.config"
# export XDG_DATA_HOME="$XDG_CONFIG_HOME/.local/share"
# export XDG_CACHE_HOME="$XDG_CONFIG_HOME/.cache"

export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}

export ZDOTDIR="${XDG_CONFIG_HOME:-${HOME}/.config}/zsh"
export CODEDIR="$HOME/Code"

# 1Password SSH Agent
export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

# Zim configuration
export ZIM_HOME="${XDG_CACHE_HOME}/zim"
export ZIM_CONFIG_FILE="${XDG_CONFIG_HOME}/zsh/.zimrc"

export HISTFILE="$ZDOTDIR/.zhistory" # History filepath
export HISTSIZE=10000                # Maximum events for internal history
export SAVEHIST=10000                # Maximum events in history file
