[extensions]
vscode = [
    # Themes
    "catppuccin.catppuccin-vsc",
    # Formatting & Linting
    "dbaeumer.vscode-eslint",
    "esbenp.prettier-vscode",
    # Language Support
    "tamasfe.even-better-toml",
    "elixir-tools.elixir-tools",
]


