[packages.brew]
tap = [
  "jesseduffield/lazygit"
]
core = [
  "git",
  "mas"
]
shell = [
  "zsh",
  "starship",
  "zoxide"
]
command = [
  "bat",
  "eza",
  "fzf",
  "ripgrep",
  "htop"
]
vcs = [
  "diff-so-fancy",
  "gh",
  "git-delta",
  "lazygit"
]
editor = [
  "neovim"
]
database = [
  "pgcli",
  "postgresql@15",
  "redis"
]
runtime = [
  "mise"
]
rust = [
  "rustup"
]
tools = [
  "jq"
]

[packages.cask]
browser = [
  "firefox@developer-edition",
  "google-chrome"
]
security = [
  "1password-cli",
  "expressvpn"
]
development = [
  "beekeeper-studio",
  "cursor",
  "docker",
  "postman",
  "visual-studio-code",
  "zed"
]
productivity = [
  "cleanshot",
  "dash",
  "notion",
  "raycast"
]
communication = [
  "discord",
  "slack",
  "telegram"
]
media = [
  "spotify"
]
font = [
  "font-fira-code-nerd-font"
]
terminal = [
  "warp"
]
design = [
  "adobe-creative-cloud",
  "sf-symbols"
]
