"$schema" = 'https://starship.rs/config-schema.json'

format = """
[  ](bg:mantle fg:text)\
[](fg:crust bg:prev_bg)\
[](fg:prev_bg bg:crust)\
$directory\
$git_branch${custom.git_uncommitted}\
[](fg:prev_bg bg:crust)\
$git_state\
$fill\
${elixir}\
${custom.react}\
${nodejs}\
${ruby}\
${custom.git_email}\
$line_break
$character
"""

add_newline = false
palette = "catppuccin_mocha"

[fill]
symbol = '█'
style = 'fg:mantle'

[character]
format = "$symbol "
vimcmd_symbol = '[ N:](bold green) '
vimcmd_replace_one_symbol = '[ R:](bold blue) '

[directory]
format = "[ $path ]($style)[](fg:crust bg:prev_bg)"
truncate_to_repo = false
truncation_length = 2
# truncation_symbol = "../"
home_symbol = "~"
style = "bg:mantle fg:subtext0"

[git_branch]
format = '[](fg:prev_bg bg:crust)[ $symbol$branch(:$remote_branch) ]($style)'
symbol = " "
style = "fg:subtext0 bg:mantle"

[custom.git_uncommitted]
description = "Display the number of uncommitted changed files"
command = "git status --porcelain | wc -l"
when = "git rev-parse --git-dir 2> /dev/null"
symbol = "󰦒"
format = '[$symbol$output ]($style)[](fg:crust bg:prev_bg)'
style = "fg:subtext0 bg:mantle"

[custom.git_email]
description = "Display the git user email"
command = "git config user.email"
when = "git rev-parse --git-dir 2> /dev/null"
symbol = "  "
format = "[](fg:mantle bg:crust)[](fg:crust bg:mantle)[$symbol $output ](bg:mantle fg:subtext0)"

[nodejs]
symbol = " "
version_format = "${major}.${minor}"
format = "[](fg:mantle bg:crust)[](fg:crust bg:mantle)[$symbol( $version )]($style)"
style = "bg:mantle fg:subtext0"

[elixir]
symbol = " "
version_format = "${major}.${minor}"
format = "[](fg:mantle bg:crust)[](fg:crust bg:mantle)[$symbol( $version )]($style)"
style = "bg:mantle fg:subtext0"

[custom.react]
description = "Detects and shows React version"
command = "jq -r '.dependencies.react // .devDependencies.react' package.json | sed -E 's/[^0-9.]//g' | cut -d. -f1,2"
when = "test -f package.json"
symbol = " "
format = "[](fg:mantle bg:crust)[](fg:crust bg:mantle)[$symbol( $output )]($style)"
style = "bg:mantle fg:subtext0"

# Palette definitions
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
