#!/usr/bin/env zsh

# +---------+
# | SETOPTS |
# +---------+

source $ZDOTDIR/options.zsh

# +---------+
# | ALIASES |
# +---------+

source $ZDOTDIR/aliases.zsh

# +-----------------+
# | ZIM FRAMEWORK |
# +----------------+
# The prefix for the alias from zim builtin git module
# zstyle ':zim:zmodule' use 'degit'
export ZIM_CONFIG_FILE="${XDG_CONFIG_HOME}/zsh/.zimrc"
export ZIM_HOME="${XDG_CACHE_HOME}/zim"

# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
    https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi

# Install missing modules and update ${ZIM_HOME}/init.zsh if missing or outdated.
[[ ~/.zimrc -nt ~/.zim/init.zsh ]] && source ~/.zim/zimfw.zsh init -q

# Initialize modules.
source ${ZIM_HOME}/init.zsh

## init zsh-abbr
source ${ZIM_HOME}/modules/zsh-abbr/zsh-abbr.zsh

# +-----------------+
# | INITIALIZATION |
# +----------------+

# Initialize fzf key bindings and fuzzy completion
source <(fzf --zsh)

# Initialize mise
eval "$(/opt/homebrew/bin/mise activate zsh)"

# Initialize starship
eval "$(starship init zsh)"

# Initialize 1Password
eval "$(op completion zsh)"
compdef _op op
