[[cable_channel]]
name = "abbr"
source_command = 'zsh -i -c abbr'
interactive = true

[[cable_channel]]
name = "brew-list"
source_command = 'brew list --versions'
preview_command = 'brew info {0}'

[[cable_channel]]
name = "functions"
source_command = '''
for file in ~/.config/zsh/functions/*.zsh; do
  if [[ -f "$file" ]]; then
    func_name=$(basename "$file" .zsh)
    
    # Extract purpose
    desc=$(grep -m1 "^# Purpose:" "$file" | sed "s/^# Purpose: //" | head -1)
    if [[ -z "$desc" ]]; then
      desc="Custom shell function"
    fi
    
    # Extract tags
    tags=$(grep -m1 "^# Tags:" "$file" | sed "s/^# Tags: //" | head -1)
    
    # Format output with tags for searchability
    if [[ -n "$tags" ]]; then
      echo "$func_name - $desc [tags: $tags]"
    else
      echo "$func_name - $desc"
    fi
  fi
done
'''
preview_command = 'cat ~/.config/zsh/functions/{0}.zsh | bat --language bash --color=always --style=numbers'
interactive = true
