[[cable_channel]]
name = "abbr"
source_command = 'zsh -i -c abbr'
interactive = true

[[cable_channel]]
name = "brew-list"
source_command = 'brew list --versions'
preview_command = 'brew info {0}'

[[cable_channel]]
name = "ports"
source_command = "lsof -i -P -n | grep LISTEN | awk '{printf \"PID: %-8s CMD: %-20s USER: %-10s PORT: %-15s ADDR: %s\\n\", $2, $1, $3, $9, $10}'"
preview_command = """
echo "=== Process Details ==="
ps -p {2} -o pid,ppid,user,start,command 2>/dev/null || echo 'Process not found'
echo ""
echo "=== Network Connections ==="
lsof -p {2} -a -i 2>/dev/null | head -10
"""
on_selection = "kill -9 {2}"
description = "Kill processes with detailed info"
