#!/usr/bin/env bash

ITEM_DIR="$CONFIG_DIR/items"     # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="SF Compact Display" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
# PADDINGS=3                     # All paddings use this value (icon, label, background)

source "$CONFIG_DIR/colors.sh"

# Configure general bar appearance.

bar=(
  height=40
  notch_display_height=40
  notch_offset=-7
  color="$BAR_COLOR"
  shadow=off
  position=top
  sticky=on
  padding_right=2
  padding_left=2
  margin=10
  corner_radius=8
  topmost=window
  blur_radius=0
  y_offset=8
)

sketchybar --bar "${bar[@]}"

# Setting up default item properties
defaults=(
  updates=when_shown

  # icon
  icon.drawing=off
  icon.padding_left=0
  icon.padding_right=0
  icon.font="$FONT:Regular:14.0"

  # label/text
  label.font="$FONT:Regular:14.0"
  label.color=$LABEL_COLOR

  # padding
  label.padding_left=8
  label.padding_right=8
  padding_right=2
  padding_left=2

  # background
  background.height=24
  background.corner_radius=5
  background.border_width=2

  # popup
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on

  scroll_texts=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/space.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/network.sh"
source "$ITEM_DIR/mic.sh"
source "$ITEM_DIR/volume.sh"

# Automatically apply configuration changes
sketchybar --hotload on

# Force all scripts to run the first time (never do this in a script)
sketchybar --update

# Initialize focused workspace
sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)
